
on:
- push
- pull_request

# jobs:
#   my-job:
#     runs-on: ubuntu-latest
#     container: alpine
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#       - name: my-step
#         run: which npm

# jobs:
#   example_matrix:
#     strategy:
#       matrix:
#         version: [10, 12, 14]
#     runs-on: ubuntu-latest
#     steps:
#       - id: my-step-version-1
#         name: my-step-version-${{ matrix.version }}
#         run: echo ${{ matrix.version }}; env

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - id: my-step-version-1
        name: foo
        run: echo hello
  bar:
    runs-on: ubuntu-latest
    steps:
      - id: my-step-version-1
        name: bar
        run: echo world
