
on:
  push

# jobs:
#   my-job:
#     runs-on: ubuntu-latest
#     container: alpine
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#       - name: my-step
#         run: which npm

jobs:
  example_matrix:
    strategy:
      matrix:
        version: [10, 12, 14]
    runs-on: ubuntu-latest
    steps:
      - id: my-step-version-${{ matrix.version }}
        name: my-step-version-${{ matrix.version }}
        run: echo ${{ matrix.version }}
