on:
  push

jobs:
  my-job:
    runs-on: ubuntu-latest
    container: alpine
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: my-step
        run: which npm
